export const PROFILE_RESOURCE_NAMES = {
  USER_PROFILE: 'USER_PROFILE',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  TRANSLATION_ALREADY_EXISTS: 'PROFILE_TRANSLATION_ALREADY_EXISTS',
  TRANSLATION_NOT_FOUND: 'PROFILE_TRANSLATION_NOT_FOUND',
} as const;

export const PROFILE_UPLOAD_CONFIG = {
  MAX_FILE_SIZE: 2 * 1024 * 1024, // 2MB
  ALLOWED_FILE_TYPES: /\/(jpg|jpeg|png|webp)$/,
  UPLOAD_PATH: './uploads/avatars',
} as const;
